/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `LuatraumaReleases`'s JSON-Schema
 * via the `definition` "release-artifact".
 */
export type ReleaseArtifact = ReleaseArtifactDotnetPublishGzippedTarball;

export interface LuatraumaReleases {
  channels: Channels;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `LuatraumaReleases`'s JSON-Schema
 * via the `definition` "channels".
 */
export interface Channels {
  [k: string]: Channel;
}
/**
 * This interface was referenced by `LuatraumaReleases`'s JSON-Schema
 * via the `definition` "channel".
 */
export interface Channel {
  displayName: string;
  releases: {
    [k: string]: Release;
  };
}
/**
 * This interface was referenced by `LuatraumaReleases`'s JSON-Schema
 * via the `definition` "release".
 */
export interface Release {
  published: boolean;
  displayName?: string;
  metadata?: {
    [k: string]: unknown;
  };
  artifacts: ReleaseArtifact[];
}
/**
 * This interface was referenced by `LuatraumaReleases`'s JSON-Schema
 * via the `definition` "release-artifact-dotnet-publish-gzipped-tarball".
 */
export interface ReleaseArtifactDotnetPublishGzippedTarball {
  type: ("61cfe85c-a7e6-4f8f-8bc7-ad47821afc7d" | "f57e80f6-8455-4f14-88e1-3cfd629faaa5") & string;
  target: DotnetRid;
  source?: string;
  downloadUrl: string;
  signatureUrl: string;
}

/**
 * This interface was referenced by `LuatraumaReleases`'s JSON-Schema
 * via the `definition` "dotnet-rid".
 */
export enum DotnetRid {
  Windows64 = "win-x64",
  Linux64 = "linux-x64",
  Mac64 = "osx-x64",
}
/**
 * This interface was referenced by `LuatraumaReleases`'s JSON-Schema
 * via the `definition` "release-artifact-type".
 */
export enum ReleaseArtifactType {
  ClientBuildGzippedTarball = "61cfe85c-a7e6-4f8f-8bc7-ad47821afc7d",
  ServerBuildGzippedTarball = "f57e80f6-8455-4f14-88e1-3cfd629faaa5",
}
